Week 1 (28/02/2025) - Creating arrays and matrices using numpy built-in functions

In [4]:
import numpy as np

# A simple, straightforward way to create a numpy array is by the array() function.
x = np.array([1, 2, 3, 4])
print(x)
# If floats are present in the array, each entry is converted to the highest precision float.
# It is also possible to convert integer arrays into float arrays by setting dtype="float" or dtype=np.flo.
y = np.array([1, 2.5, 3.14, 4])
print(y)

# It is possible to initialize a zero array/matrix through the zeros() function.
z_array = np.zeros(10, dtype=np.uint8) # array of 10 zeros
print(z_array)
z_matrix = np.zeros((3, 3), dtype=np.uint8) # 3x3 zero matrix
print(z_matrix)

# It is possible to employ the full() function in order to fill an array/matrix with specific values.
f_5 = np.full((5, 5), 5) # 5x5 matrix whose entries are all equal to 5
print(f_5)

# It is possible to create an array whose values fall within a given range through the arange() function, which can also specify steps for taking the values (optional).
s_1 = np.arange(0, 20) # array whose entries range from 0 to 19 (recall that the upper bound of a range is always excluded)
print(s_1)
s_2 = np.arange(0, 20, 2) # same as before but values are now taken with steps of 2
print(s_2)

# The linspace() function takes values from an equally divided input interval.
l = np.linspace(0, 1, 5) # array whose entries are taken from partitioning the interval [0,1] in 5 sub-intervals
print(l)

# The random.random() function creates an array choosing random values in the interval [0,1]
r_1 = np.random.random(5) # array whose entries are randomly taken from [0,1]
print(r_1)

# The random.randint() function works similarly to random.random() but allows to manually choose the interval.
r_2 = np.random.randint(1, 10, 3) # array of 3 elements randomly chosen from the interval [1, 10]
print(r_2)

# The np.eye() function allows to create an identity matrix.
I = np.eye(3) # 3x3 identity matrix
print(I)

# The empty() function creates an "empty" array whose values are either very small or very large.
e = np.empty(2) # "empty" array of 2 elements

[1 2 3 4]
[1.   2.5  3.14 4.  ]
[0 0 0 0 0 0 0 0 0 0]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  2  4  6  8 10 12 14 16 18]
[0.   0.25 0.5  0.75 1.  ]
[0.61673339 0.1497587  0.13192762 0.6014243  0.42443685]
[4 3 7]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
