Week 2 (05/03/2025) - Properties of numpy arrays

In [1]:
import numpy as np

np.random.seed(0) # random seed for creating random arrays starting from its value (if fixed), it allows to repeat the code

x1 = np.random.randint(10, size=6) # one-dimensional array containing 6 elements from the interval [0, 10)
print(x1)

# Recall: f'' is the standard Python way for string formatting.

# Information about the first array.
print(f'The dimension is {x1.ndim}')
print(f'The shape is {x1.shape}') # this function returns how many elements each dimension of the array contains
print(f'The size is {x1.size}') # this function returns the total number of elements in the array

[5 0 3 3 7 9]
The dimension is 1
The shape is (6,)
The size is 6


In [6]:
import numpy as np

np.random.seed(0)

x2 = np.random.randint(10, size=(3, 4)) # two-dimensional array (3x4 matrix) containing elements from the interval [0,10)
print(x2)

# Information about the second array.
print(f'The dimension is {x2.ndim}')
print(f'The shape is {x2.shape}')
print(f'The size is {x2.size}')

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
The dimension is 2
The shape is (3, 4)
The size is 12


In [8]:
import numpy as np

np.random.seed(0)

x3 = np.random.randint(10, size=(3, 4, 5)) # three-dimensional array containing elements from the interval [0, 10)
print(x3)

# Information about the second array.
print(f'The dimension is {x3.ndim}')
print(f'The shape is {x3.shape}')
print(f'The size is {x3.size}')

[[[5 0 3 3 7]
  [9 3 5 2 4]
  [7 6 8 8 1]
  [6 7 7 8 1]]

 [[5 9 8 9 4]
  [3 0 3 5 0]
  [2 3 8 1 3]
  [3 3 7 0 1]]

 [[9 9 0 4 7]
  [3 2 7 2 0]
  [0 4 5 5 6]
  [8 4 1 4 9]]]
The dimension is 3
The shape is (3, 4, 5)
The size is 60


In [13]:
import numpy as np

np.random.seed(0)

# To access elements in a one-dimensional array, it is sufficient to just specify the index, starting from index 0 for the first element.
x1 = np.random.randint(10, size=6)
print(x1)
print(x1[1]) # print the second element of the array

# To access elements in a two-dimensional array, it is required to specify indices for both dimensions within the square brackets.
x2 = np.random.randint(10, size=(3, 4))
print(x2)
print(x2[0, 0]) # print the top left element

# The aforementioned procedure generalises for n-dimensional arrays as well.
x3 = np.random.randint(10, size=(3, 4, 5))
print(x3)
print(x3[2, 3, 4]) # print the bottom right element

# In order to start from the end, it is possible to use negative indices, starting from index -1 for the last element.
print(x1[-1]) # print the last element
print(x2[-1, -1]) # print the bottom right element
print(x3[-1, -1, -1]) # print the bottom right element

[5 0 3 3 7 9]
0
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
3
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
4
9
7
4


In [24]:
import numpy as np

np.random.seed(0)

x2 = np.random.randint(10, size=(3, 4))
print(x2)

# To modify elements in an array, it is possible to set arr[i, j] = new_value.
x2[0, 0] = 99
print(x2)

# Observe that if the aforementioned procedure is done with floats, only the integer part is kept.
# In general, the structure follows the highest precision values, but created arrays are an exception as they require type conversion first.
x2[0, 0] = 3.14
print(x2) # to set 3.14, you need to specify dtype="float" or dtype=np.flo

# Similarly to Python arrays, numpy supports slicing to recover parts of the array, using the same notation as standard lists.
x1 = np.random.randint(10, size=6)
print(x1[1:4]) # extract elements from index 1 to index 4 (x1[4] is excluded) with steps=1 by default
print(x1[1:5:2]) # similar as before but with steps=2
print(x1[:5]) # extract elements up to index 5
print(x1[2:]) # extract elements from index 2 to the end
print(x1[::-1]) # using a negative steps carries out the extraction backwards (writing x1[::-1] basically prints the array backwards)

# Slicing can easily be generalised for n-dimensional arrays as well, with the idea that each dimension is identified by the corresponding index.
print(x2[:2, :3]) # extract the first 2 rows and the first 3 columns of the matrix
print(x2[:, 0]) # extract all the rows but only the first column of the matrix
print(x2[1, :]) # extract all the columns but only the second row of the matrix
print(x2[1]) # same as before but in a simpler syntax

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[[99  0  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]]
[[3 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[8 1 6]
[8 6]
[8 8 1 6 7]
[1 6 7 7]
[7 7 6 1 8 8]
[[3 0 3]
 [7 9 3]]
[3 7 2]
[7 9 3 5]
[7 9 3 5]
[[3 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[[3 0]
 [7 9]]


In [26]:
import numpy as np

np.random.seed(0)

# Slicing also allows to extract sub-matrices from matrices.
x2 = np.random.randint(10, size=(3,4))
x2_sub = x2[:2, :2] # sub-matrix composed by the first two rows and first two columns of x2
print(x2)
print(x2_sub)

# Notice, however, that, if a sub-matrix is modified, numpy modifies the whole matrix as well.
x2_sub[0, 0] = 99
print(x2_sub)
print(x2) # notice something weird?
# This comes from the fact that sub-matrices are just a "view" of the entire matrix.

# In order to modify just the sub-matrix, the copy() function must be used as well.
x2_sub = x2[:2, :2].copy()
x2_sub[0, 0] = 66
print(x2_sub)
print(x2)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[[5 0]
 [7 9]]
[[99  0]
 [ 7  9]]
[[99  0  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]]
[[66  0]
 [ 7  9]]
[[99  0  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]]


In [36]:
import numpy as np

np.random.seed(0)

# It is possible to convert one-dimensional arrays into two-dimensional arrays (and viceversa) through the reshape() function.
x1 = np.random.randint(10, size=9)
x1_grid = x1.reshape((3, 3)) # convert the array into a 3x3 matrix
print(x1)
print(x1_grid)
# Generally speaking, it is not required to specify the exact dimension so that, if you want to specify one condition, it is possible to set the jolly value "-1" for unspecified dimensions.
x1_grid = x1.reshape((3, -1)) # this can be generalised for any dimension
print(x1_grid)
x1_grid = x1.reshape((-1, 3)) # same as before but now only the  umber of columns is specified
print(x1_grid)

# Now consider the reverse case.
x2 = np.random.randint(10, size=(3, 4))
x2_linear = x2.reshape((1, -1)) # consider one-dimensional arrays as matrices with one row and n columns
print(x2)
print(x2_linear) # graphically, this is still treated as a two-dimensional array
# Notice that it is possible to perform this conversion by just writing reshape((-1)).
print(x2.reshape((-1)))

[5 0 3 3 7 9 3 5 2]
[[5 0 3]
 [3 7 9]
 [3 5 2]]
[[5 0 3]
 [3 7 9]
 [3 5 2]]
[[5 0 3]
 [3 7 9]
 [3 5 2]]
[[4 7 6 8]
 [8 1 6 7]
 [7 8 1 5]]
[[4 7 6 8 8 1 6 7 7 8 1 5]]
[4 7 6 8 8 1 6 7 7 8 1 5]


In [41]:
import numpy as np

np.random.seed(0)

# It is possible to horizontally concatenate two (or more) arrays using the concatenate() function.
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
new_array = np.concatenate([x, y]) # recall that order matters and that dimensions must match together
print(new_array)
# Observe that concatenate() also works with n-dimensional arrays.
z = np.array([[1, 2, 3], [4, 5, 6]])
new_array = np.concatenate([z, z])
print(new_array)

# Alternatively, it is possible to concatenate two (or more) arrays using the vstack() function.
x = np.array([7, 8, 9])
new_array = np.vstack([z, x])
print(new_array)
# Similarly, it is possible to perform the same action on columns using the hstack() function.
y = np.array([[99], [99]])
new_array = np.hstack([z, y])
print(new_array)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3 99]
 [ 4  5  6 99]]


In [51]:
import numpy as np

np.random.seed(0)

# It is possible to split arrays into sub-arrays through the split() function.
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
x1,x2 = np.split(x, [3]) # split array x at index 3 -> expect x[0:3] and x[3:]
print(x1)
print(x2)
x1,x2,x3 = np.split(x, [3, 6]) # same as before but the array is split at indices 3 and 6 -> expect x[0:3], x[3:6] and x[6:]
print(x1)
print(x2)
print(x3)
# Generally speaking, if k indices are specified in the split() function, then k + 1 sub-arrays will be produced.
# N.B.: if just one variable is specified in split(), then the function will create an array of arrays.
x_s = np.split(x, [3, 6])
print(x_s)

# For two-dimensional arrays, it is possible to consider vertical and horizontal splits through the vsplit()/hsplit() functions.
z = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
z1,z2 = np.vsplit(z, [1]) # vertical split with respect to row 1 -> expect z[:1] and z[1:]
print(z1)
print(z2)
z1,z2 = np.hsplit(z, [1]) # horizontal split with respect to column 1 -> expect z[:, :1] and z[: 1:]
print(z1)
print(z2)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3]
[4 5 6]
[7 8 9]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[[1 2 3]]
[[4 5 6]
 [7 8 9]]
[[1]
 [4]
 [7]]
[[2 3]
 [5 6]
 [8 9]]
